server:
  port: 18080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: school
  datasource:
    url: jdbc:postgresql://localhost:5432/SCHOOL-DB
    username: db-user
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true